// Auto-generated from pikachu-cards.md — do not edit by hand
// Run scripts/migrate-cards.ts to regenerate

export interface SeedCard {
  id: number
  name: string
  set_name: string
  card_number: string
  rarity: string
  release_year: number
  price_eur: number | null
}

export const SEED_CARDS: SeedCard[] = [
  { id: 1, name: "Pikachu", set_name: "Expansion Pack", card_number: "", rarity: "Common", release_year: 1996, price_eur: null },
  { id: 2, name: "Pikachu", set_name: "Sample Set", card_number: "", rarity: "Common", release_year: 1998, price_eur: null },
  { id: 3, name: "Pikachu", set_name: "Sample Set", card_number: "", rarity: "", release_year: 1998, price_eur: null },
  { id: 5, name: "Pikachu", set_name: "Unnumbered Promos", card_number: "", rarity: "", release_year: 1999, price_eur: null },
  { id: 4, name: "Pikachu", set_name: "Base Set", card_number: "58/102", rarity: "Common", release_year: 1999, price_eur: 9.85 },
  { id: 6, name: "Pikachu", set_name: "P Promotional", card_number: "004/P", rarity: "", release_year: 1999, price_eur: null },
  { id: 7, name: "Pikachu", set_name: "Wizards Promo", card_number: "1", rarity: "Promo", release_year: 1999, price_eur: 22.13 },
  { id: 8, name: "Pikachu", set_name: "Jungle", card_number: "60/64", rarity: "Common", release_year: 1999, price_eur: 1.62 },
  { id: 9, name: "Pikachu", set_name: "Wizards Promo", card_number: "4", rarity: "Promo", release_year: 1999, price_eur: 64.29 },
  { id: 10, name: "Lt. Surge\\'s Pikachu", set_name: "Gym Heroes", card_number: "81/132", rarity: "Common", release_year: 1999, price_eur: 7.5 },
  { id: 12, name: "Pikachu", set_name: "Wizards Promo", card_number: "26", rarity: "Promo", release_year: 1999, price_eur: 26.43 },
  { id: 415, name: "Pikachu", set_name: "Vending Series 1", card_number: "", rarity: "", release_year: 1999, price_eur: null },
  { id: 513, name: "Pikachu World Collection", set_name: "World Collection Promos", card_number: "", rarity: "Promo", release_year: 1999, price_eur: null },
  { id: 13, name: "Pikachu", set_name: "Wizards Promo", card_number: "27", rarity: "Promo", release_year: 1999, price_eur: 10.56 },
  { id: 11, name: "Lt. Surge\\'s Pikachu", set_name: "Gym Challenge", card_number: "84/132", rarity: "Common", release_year: 1999, price_eur: 8.92 },
  { id: 14, name: "Pikachu", set_name: "Wizards Promo", card_number: "28", rarity: "Promo", release_year: 1999, price_eur: 35.09 },
  { id: 15, name: "Pikachu", set_name: "Base Set 2", card_number: "87/130", rarity: "Common", release_year: 2000, price_eur: 2.23 },
  { id: 416, name: "Pikachu", set_name: "Vending Series 2", card_number: "", rarity: "", release_year: 2000, price_eur: null },
  { id: 16, name: "Pikachu", set_name: "Totodile Half Deck", card_number: "", rarity: "", release_year: 2000, price_eur: null },
  { id: 417, name: "Pikachu", set_name: "Vending Series 3", card_number: "", rarity: "", release_year: 2000, price_eur: null },
  { id: 17, name: "Pikachu World Collection", set_name: "Pikachu World 2000", card_number: "", rarity: "", release_year: 2000, price_eur: null },
  { id: 18, name: "Pikachu", set_name: "Neo Genesis", card_number: "70/111", rarity: "Common", release_year: 2000, price_eur: 5.4 },
  { id: 19, name: "Pikachu", set_name: "P Promotional", card_number: "021/P", rarity: "", release_year: 2001, price_eur: null },
  { id: 20, name: "Pikachu", set_name: "Expedition", card_number: "124/165", rarity: "Common", release_year: 2001, price_eur: 5.22 },
  { id: 21, name: "Pikachu", set_name: "P Promotional", card_number: "038/P", rarity: "", release_year: 2002, price_eur: null },
  { id: 22, name: "Pikachu", set_name: "P Promotional", card_number: "044/P", rarity: "", release_year: 2002, price_eur: null },
  { id: 24, name: "Pikachu", set_name: "Legendary Collection", card_number: "86/110", rarity: "Common", release_year: 2002, price_eur: 3.17 },
  { id: 23, name: "Pikachu", set_name: "McDonald\\'s Pokémon-e", card_number: "010/018", rarity: "", release_year: 2002, price_eur: null },
  { id: 25, name: "Pikachu", set_name: "Skyridge", card_number: "84/144", rarity: "Common", release_year: 2003, price_eur: 20.15 },
  { id: 26, name: "Pikachu", set_name: "EX Sandstorm", card_number: "72/100", rarity: "Common", release_year: 2003, price_eur: 5.1 },
  { id: 27, name: "Pikachu", set_name: "EX Team Magma vs Aqua", card_number: "43/95", rarity: "Common", release_year: 2004, price_eur: null },
  { id: 28, name: "Pikachu", set_name: "Latios Half Deck", card_number: "6/10", rarity: "", release_year: 2004, price_eur: null },
  { id: 29, name: "Pikachu", set_name: "ADV-P Promotional", card_number: "023/ADV-P", rarity: "", release_year: 2004, price_eur: null },
  { id: 30, name: "Pikachu", set_name: "ADV-P Promotional", card_number: "024/ADV-P", rarity: "", release_year: 2004, price_eur: null },
  { id: 31, name: "Pikachu", set_name: "Nintendo Promo", card_number: "012", rarity: "Promo", release_year: 2004, price_eur: 114.45 },
  { id: 32, name: "Pikachu", set_name: "EX FireRed & LeafGreen", card_number: "74/112", rarity: "Common", release_year: 2004, price_eur: 4.16 },
  { id: 33, name: "Pikachu", set_name: "EX Emerald", card_number: "60/106", rarity: "Common", release_year: 2005, price_eur: 2.77 },
  { id: 34, name: "Pikachu", set_name: "POP Series 2", card_number: "16/17", rarity: "Common", release_year: 2005, price_eur: 27.88 },
  { id: 35, name: "PokéPark\\'s Pikachu", set_name: "PokéPark Forest", card_number: "004/009", rarity: "", release_year: 2005, price_eur: null },
  { id: 36, name: "Pikachu δ", set_name: "EX Legend Maker", card_number: "93/92", rarity: "Secret", release_year: 2006, price_eur: 59.8 },
  { id: 37, name: "Pikachu δ", set_name: "Nintendo Promo", card_number: "035", rarity: "Promo", release_year: 2006, price_eur: 212.39 },
  { id: 38, name: "Pikachu", set_name: "EX Holon Phantoms", card_number: "78/110", rarity: "Common", release_year: 2006, price_eur: 3.94 },
  { id: 39, name: "Pikachu δ", set_name: "EX Holon Phantoms", card_number: "79/110", rarity: "Common", release_year: 2006, price_eur: 5.58 },
  { id: 40, name: "Pikachu★ (Shining)", set_name: "EX Holon Phantoms", card_number: "104/110", rarity: "★", release_year: 2006, price_eur: 1715.31 },
  { id: 41, name: "Pikachu", set_name: "POP Series 4", card_number: "13/17", rarity: "Common", release_year: 2006, price_eur: 37.27 },
  { id: 42, name: "PokéPark\\'s Pikachu", set_name: "PCG-P Promotional", card_number: "043/PCG-P", rarity: "", release_year: 2006, price_eur: null },
  { id: 43, name: "Pikachu", set_name: "EX Power Keepers", card_number: "57/108", rarity: "Common", release_year: 2007, price_eur: 3.55 },
  { id: 44, name: "Pikachu", set_name: "PCG-P Promotional", card_number: "123/PCG-P", rarity: "", release_year: 2007, price_eur: null },
  { id: 45, name: "Pikachu", set_name: "POP Series 5", card_number: "12/17", rarity: "Common", release_year: 2007, price_eur: 128.32 },
  { id: 46, name: "Pikachu δ", set_name: "POP Series 5", card_number: "13/17", rarity: "Common", release_year: 2007, price_eur: 37.41 },
  { id: 47, name: "Pikachu", set_name: "Mysterious Treasures", card_number: "94/123", rarity: "Common", release_year: 2007, price_eur: 3.63 },
  { id: 48, name: "Pikachu", set_name: "DP Promo", card_number: "DP16", rarity: "Promo", release_year: 2007, price_eur: null },
  { id: 49, name: "Pikachu", set_name: "DP-P Promotional", card_number: "048/DP-P", rarity: "", release_year: 2007, price_eur: null },
  { id: 50, name: "Pikachu", set_name: "DP-P Promotional", card_number: "057/DP-P", rarity: "", release_year: 2008, price_eur: null },
  { id: 51, name: "Pikachu", set_name: "POP Series 6", card_number: "9/17", rarity: "Common", release_year: 2008, price_eur: 36.99 },
  { id: 52, name: "Pikachu", set_name: "Majestic Dawn", card_number: "70/100", rarity: "Common", release_year: 2008, price_eur: 1.15 },
  { id: 53, name: "Pikachu", set_name: "DP-P Promotional", card_number: "095/DP-P", rarity: "", release_year: 2008, price_eur: null },
  { id: 54, name: "Pikachu", set_name: "DP-P Promotional", card_number: "098/DP-P", rarity: "", release_year: 2008, price_eur: null },
  { id: 55, name: "Pikachu", set_name: "DP-P Promotional", card_number: "099/DP-P", rarity: "", release_year: 2008, price_eur: null },
  { id: 56, name: "Pikachu", set_name: "DP-P Promotional", card_number: "100/DP-P", rarity: "", release_year: 2008, price_eur: null },
  { id: 57, name: "Pikachu", set_name: "DP-P Promotional", card_number: "101/DP-P", rarity: "", release_year: 2008, price_eur: null },
  { id: 58, name: "Pikachu", set_name: "DP-P Promotional", card_number: "102/DP-P", rarity: "", release_year: 2008, price_eur: null },
  { id: 59, name: "Pikachu", set_name: "11th Movie Set", card_number: "003/009", rarity: "", release_year: 2008, price_eur: null },
  { id: 261, name: "Pikachu", set_name: "DP-P Promotional", card_number: "103/DP-P", rarity: "", release_year: 2008, price_eur: null },
  { id: 262, name: "Pikachu", set_name: "DP-P Promotional", card_number: "104/DP-P", rarity: "", release_year: 2008, price_eur: null },
  { id: 263, name: "Pikachu", set_name: "DP-P Promotional", card_number: "105/DP-P", rarity: "", release_year: 2008, price_eur: null },
  { id: 264, name: "Pikachu", set_name: "DP-P Promotional", card_number: "106/DP-P", rarity: "", release_year: 2008, price_eur: null },
  { id: 265, name: "Pikachu", set_name: "DP-P Promotional", card_number: "107/DP-P", rarity: "", release_year: 2008, price_eur: null },
  { id: 266, name: "Pikachu", set_name: "DP-P Promotional", card_number: "108/DP-P", rarity: "", release_year: 2008, price_eur: null },
  { id: 267, name: "Pikachu", set_name: "DP-P Promotional", card_number: "109/DP-P", rarity: "", release_year: 2008, price_eur: null },
  { id: 268, name: "Pikachu", set_name: "DP-P Promotional", card_number: "110/DP-P", rarity: "", release_year: 2008, price_eur: null },
  { id: 60, name: "Pikachu", set_name: "Stormfront", card_number: "70/100", rarity: "Uncommon", release_year: 2008, price_eur: 3.06 },
  { id: 269, name: "Pikachu", set_name: "DP-P Promotional", card_number: "111/DP-P", rarity: "", release_year: 2008, price_eur: null },
  { id: 270, name: "Pikachu", set_name: "DP-P Promotional", card_number: "112/DP-P", rarity: "", release_year: 2008, price_eur: null },
  { id: 61, name: "Pikachu", set_name: "Rising Rivals", card_number: "112/111", rarity: "Secret", release_year: 2009, price_eur: 51.35 },
  { id: 62, name: "Flying Pikachu", set_name: "Rising Rivals", card_number: "113/111", rarity: "Secret", release_year: 2009, price_eur: 37.42 },
  { id: 63, name: "Surfing Pikachu", set_name: "Rising Rivals", card_number: "114/111", rarity: "Secret", release_year: 2009, price_eur: 86.3 },
  { id: 68, name: "Pikachu Movie", set_name: "DPt-P Promotional", card_number: "043/DPt-P", rarity: "", release_year: 2009, price_eur: null },
  { id: 64, name: "Pikachu", set_name: "Supreme Victors", card_number: "120/147", rarity: "Secret", release_year: 2009, price_eur: 1.56 },
  { id: 65, name: "Pikachu", set_name: "POP Series 9", card_number: "15/17", rarity: "Common", release_year: 2009, price_eur: 30.66 },
  { id: 66, name: "Pikachu", set_name: "Shaymin Collection Pack", card_number: "007/012", rarity: "", release_year: 2009, price_eur: null },
  { id: 69, name: "Pikachu", set_name: "Pokémon Rumble", card_number: "7/16", rarity: "", release_year: 2009, price_eur: 658.57 },
  { id: 67, name: "Pikachu", set_name: "Arceus", card_number: "71/99", rarity: "Common", release_year: 2009, price_eur: 2.1 },
  { id: 70, name: "Pikachu", set_name: "DPt-P Promotional", card_number: "016/DPt-P", rarity: "", release_year: 2009, price_eur: null },
  { id: 71, name: "Pikachu", set_name: "HGSS Promo", card_number: "HGSS03", rarity: "Promo", release_year: 2010, price_eur: null },
  { id: 72, name: "Pikachu", set_name: "HeartGold SoulSilver", card_number: "78/123", rarity: "Common", release_year: 2010, price_eur: 2.82 },
  { id: 73, name: "Pikachu", set_name: "Raichu Half Deck", card_number: "2/30", rarity: "", release_year: 2010, price_eur: null },
  { id: 74, name: "Pikachu", set_name: "Raichu Half Deck", card_number: "16/30", rarity: "", release_year: 2010, price_eur: null },
  { id: 75, name: "Shopping Pikachu", set_name: "L-P Promotional", card_number: "079/L-P", rarity: "", release_year: 2010, price_eur: null },
  { id: 77, name: "Pikachu World Collection", set_name: "Pikachu World 2010", card_number: "", rarity: "", release_year: 2010, price_eur: null },
  { id: 78, name: "Pikachu", set_name: "Pikachu World", card_number: "001/009", rarity: "", release_year: 2010, price_eur: null },
  { id: 79, name: "Pikachu", set_name: "Pikachu World", card_number: "002/009", rarity: "", release_year: 2010, price_eur: null },
  { id: 80, name: "Pikachu", set_name: "Pikachu World", card_number: "003/009", rarity: "", release_year: 2010, price_eur: null },
  { id: 81, name: "Pikachu", set_name: "Pikachu World", card_number: "004/009", rarity: "", release_year: 2010, price_eur: null },
  { id: 82, name: "Pikachu", set_name: "Pikachu World", card_number: "005/009", rarity: "", release_year: 2010, price_eur: null },
  { id: 83, name: "Pikachu", set_name: "Pikachu World", card_number: "006/009", rarity: "", release_year: 2010, price_eur: null },
  { id: 84, name: "Pikachu", set_name: "Pikachu World", card_number: "007/009", rarity: "", release_year: 2010, price_eur: null },
  { id: 85, name: "Pikachu", set_name: "Pikachu World", card_number: "008/009", rarity: "", release_year: 2010, price_eur: null },
  { id: 86, name: "Pikachu", set_name: "Pikachu World", card_number: "009/009", rarity: "", release_year: 2010, price_eur: null },
  { id: 398, name: "Pikachu", set_name: "Movie Promo", card_number: "", rarity: "Promo", release_year: 2010, price_eur: null },
  { id: 76, name: "Pikachu", set_name: "Undaunted", card_number: "61/90", rarity: "Common", release_year: 2010, price_eur: 3.22 },
  { id: 423, name: "Pikachu", set_name: "Deck Kit", card_number: "", rarity: "", release_year: 2010, price_eur: null },
  { id: 87, name: "Pikachu", set_name: "Black & White", card_number: "115/114", rarity: "Secret", release_year: 2011, price_eur: 206.86 },
  { id: 88, name: "\\'s Pikachu", set_name: "BW-P Promotional", card_number: "BW-P", rarity: "", release_year: 2011, price_eur: null },
  { id: 399, name: "Pikachu", set_name: "Movie Promo", card_number: "", rarity: "Promo", release_year: 2011, price_eur: null },
  { id: 89, name: "Pikachu", set_name: "BW-P Promotional", card_number: "229/BW-P", rarity: "", release_year: 2011, price_eur: null },
  { id: 90, name: "Pikachu", set_name: "Next Destinies", card_number: "39/99", rarity: "Common", release_year: 2012, price_eur: 2.82 },
  { id: 92, name: "Pikachu", set_name: "BW Promo", card_number: "BW54", rarity: "Promo", release_year: 2012, price_eur: 52.68 },
  { id: 93, name: "Pikachu", set_name: "BW-P Promotional", card_number: "120/BW-P", rarity: "", release_year: 2012, price_eur: null },
  { id: 400, name: "Pikachu", set_name: "Movie Promo", card_number: "", rarity: "Promo", release_year: 2012, price_eur: null },
  { id: 94, name: "Pikachu", set_name: "BW-P Promotional", card_number: "151/BW-P", rarity: "", release_year: 2012, price_eur: null },
  { id: 271, name: "Pikachu", set_name: "BW-P Promotional", card_number: "164/BW-P", rarity: "", release_year: 2012, price_eur: null },
  { id: 91, name: "Pikachu", set_name: "Legendary Treasures", card_number: "RC7/RC25", rarity: "Radiant", release_year: 2012, price_eur: 23.56 },
  { id: 272, name: "Pikachu", set_name: "BW-P Promotional", card_number: "165/BW-P", rarity: "", release_year: 2012, price_eur: null },
  { id: 273, name: "Pikachu", set_name: "BW-P Promotional", card_number: "166/BW-P", rarity: "", release_year: 2012, price_eur: null },
  { id: 95, name: "Pikachu", set_name: "BW Promo", card_number: "BW77", rarity: "Promo", release_year: 2012, price_eur: null },
  { id: 96, name: "Pikachu", set_name: "Boundaries Crossed", card_number: "50/149", rarity: "Common", release_year: 2012, price_eur: 2.29 },
  { id: 97, name: "Pikachu", set_name: "Everyone\\'s Exciting Battle", card_number: "016/047", rarity: "", release_year: 2013, price_eur: null },
  { id: 98, name: "Pikachu (Nagoya)", set_name: "BW-P Promotional", card_number: "BW-P", rarity: "", release_year: 2013, price_eur: null },
  { id: 274, name: "Pikachu", set_name: "BW-P Promotional", card_number: "200/BW-P", rarity: "", release_year: 2013, price_eur: null },
  { id: 275, name: "Pikachu", set_name: "BW-P Promotional", card_number: "201/BW-P", rarity: "", release_year: 2013, price_eur: null },
  { id: 276, name: "Pikachu", set_name: "BW-P Promotional", card_number: "202/BW-P", rarity: "", release_year: 2013, price_eur: null },
  { id: 424, name: "Pikachu", set_name: "Deck Kit", card_number: "", rarity: "", release_year: 2013, price_eur: null },
  { id: 99, name: "Pikachu (BEAMS)", set_name: "BW-P Promotional", card_number: "BW-P", rarity: "", release_year: 2013, price_eur: null },
  { id: 277, name: "Pikachu", set_name: "BW-P Promotional", card_number: "203/BW-P", rarity: "", release_year: 2013, price_eur: null },
  { id: 364, name: "Pikachu", set_name: "League Promo", card_number: "", rarity: "Promo", release_year: 2013, price_eur: null },
  { id: 100, name: "Pikachu", set_name: "BW-P Promotional", card_number: "163/BW-P", rarity: "", release_year: 2013, price_eur: null },
  { id: 401, name: "Pikachu", set_name: "Movie Promo", card_number: "", rarity: "Promo", release_year: 2013, price_eur: null },
  { id: 278, name: "Pikachu", set_name: "BW-P Promotional", card_number: "228/BW-P", rarity: "", release_year: 2013, price_eur: null },
  { id: 101, name: "Pikachu", set_name: "XY", card_number: "42/146", rarity: "Common", release_year: 2013, price_eur: 6.67 },
  { id: 102, name: "Pikachu", set_name: "McDonald\\'s 2014", card_number: "5/12", rarity: "", release_year: 2014, price_eur: null },
  { id: 103, name: "Pikachu", set_name: "M Master Deck Build Box", card_number: "011/049", rarity: "", release_year: 2014, price_eur: null },
  { id: 365, name: "Pikachu", set_name: "League Promo", card_number: "", rarity: "Promo", release_year: 2014, price_eur: null },
  { id: 369, name: "Pikachu", set_name: "Pokémon Center", card_number: "", rarity: "", release_year: 2014, price_eur: null },
  { id: 104, name: "Pikachu", set_name: "Furious Fists", card_number: "27/111", rarity: "Common", release_year: 2014, price_eur: 4.76 },
  { id: 290, name: "Pitch\\'s Pikachu (Okinawa)", set_name: "XY-P Promotional", card_number: "XY-P", rarity: "", release_year: 2014, price_eur: null },
  { id: 291, name: "Pitch\\'s Pikachu (Osaka)", set_name: "XY-P Promotional", card_number: "XY-P", rarity: "", release_year: 2014, price_eur: null },
  { id: 402, name: "Pikachu", set_name: "Movie Promo", card_number: "", rarity: "Promo", release_year: 2014, price_eur: null },
  { id: 105, name: "Team Japan\\'s Pikachu", set_name: "XY-P Promotional", card_number: "050/XY-P", rarity: "", release_year: 2014, price_eur: null },
  { id: 106, name: "PokéTele\\'s AD Pikachu", set_name: "XY-P Promotional", card_number: "056/XY-P", rarity: "", release_year: 2014, price_eur: null },
  { id: 282, name: "Pikachu", set_name: "XY-P Promotional", card_number: "050/XY-P", rarity: "", release_year: 2014, price_eur: null },
  { id: 283, name: "Pikachu", set_name: "XY-P Promotional", card_number: "056/XY-P", rarity: "", release_year: 2014, price_eur: null },
  { id: 335, name: "Pikachu", set_name: "World Championship 2014", card_number: "", rarity: "Promo", release_year: 2014, price_eur: null },
  { id: 292, name: "Pikachu", set_name: "XY-P Promotional", card_number: "XY-P", rarity: "", release_year: 2014, price_eur: null },
  { id: 408, name: "Pikachu JUMBO", set_name: "Jumbo Promo", card_number: "", rarity: "Jumbo", release_year: 2014, price_eur: null },
  { id: 107, name: "Pikachu", set_name: "XY-P Promotional", card_number: "068/XY-P", rarity: "", release_year: 2014, price_eur: null },
  { id: 108, name: "Pikachu", set_name: "XY-P Promotional", card_number: "069/XY-P", rarity: "", release_year: 2014, price_eur: null },
  { id: 109, name: "Pikachu", set_name: "XY-P Promotional", card_number: "070/XY-P", rarity: "", release_year: 2014, price_eur: null },
  { id: 293, name: "Pikachu", set_name: "XY-P Promotional", card_number: "XY-P", rarity: "", release_year: 2014, price_eur: null },
  { id: 110, name: "Pikachu", set_name: "XY-P Promotional", card_number: "090/XY-P", rarity: "", release_year: 2014, price_eur: null },
  { id: 370, name: "Pikachu", set_name: "Pokémon Center", card_number: "", rarity: "", release_year: 2014, price_eur: null },
  { id: 111, name: "Warm Pikachu", set_name: "XY-P Promotional", card_number: "094/XY-P", rarity: "", release_year: 2015, price_eur: null },
  { id: 112, name: "Warm Pikachu", set_name: "XY-P Promotional", card_number: "095/XY-P", rarity: "", release_year: 2015, price_eur: null },
  { id: 113, name: "Warm Pikachu", set_name: "XY-P Promotional", card_number: "096/XY-P", rarity: "", release_year: 2015, price_eur: null },
  { id: 114, name: "Warm Pikachu", set_name: "XY-P Promotional", card_number: "097/XY-P", rarity: "", release_year: 2015, price_eur: null },
  { id: 115, name: "Mega Tokyo Pikachu", set_name: "XY-P Promotional", card_number: "098/XY-P", rarity: "", release_year: 2015, price_eur: null },
  { id: 116, name: "Cosplay Pikachu", set_name: "XY-P Promotional", card_number: "099/XY-P", rarity: "", release_year: 2015, price_eur: null },
  { id: 294, name: "Pikachu", set_name: "XY-P Promotional", card_number: "XY-P", rarity: "", release_year: 2015, price_eur: null },
  { id: 450, name: "Pikachu", set_name: "Store Championship", card_number: "", rarity: "Promo", release_year: 2015, price_eur: null },
  { id: 117, name: "Magikarp Pretending Pikachu", set_name: "XY-P Promotional", card_number: "150/XY-P", rarity: "", release_year: 2015, price_eur: null },
  { id: 118, name: "Gyarados Pretending Pikachu", set_name: "XY-P Promotional", card_number: "151/XY-P", rarity: "", release_year: 2015, price_eur: null },
  { id: 295, name: "Pikachu", set_name: "XY-P Promotional", card_number: "XY-P", rarity: "", release_year: 2015, price_eur: null },
  { id: 119, name: "Pikachu", set_name: "Roaring Skies", card_number: "20/108", rarity: "Common", release_year: 2015, price_eur: 1.81 },
  { id: 120, name: "Pikachu", set_name: "XY-P Promotional", card_number: "175/XY-P", rarity: "", release_year: 2015, price_eur: null },
  { id: 121, name: "McDonald\\'s 2015", set_name: "McDonald\\'s 2015", card_number: "6/12", rarity: "", release_year: 2015, price_eur: null },
  { id: 371, name: "Pikachu", set_name: "Pokémon Center", card_number: "", rarity: "", release_year: 2015, price_eur: null },
  { id: 296, name: "Pikachu", set_name: "XY-P Promotional", card_number: "XY-P", rarity: "", release_year: 2015, price_eur: null },
  { id: 403, name: "Pikachu", set_name: "Movie Promo", card_number: "", rarity: "Promo", release_year: 2015, price_eur: null },
  { id: 297, name: "Pikachu", set_name: "XY-P Promotional", card_number: "XY-P", rarity: "", release_year: 2015, price_eur: null },
  { id: 336, name: "Pikachu", set_name: "World Championship 2015", card_number: "", rarity: "Promo", release_year: 2015, price_eur: null },
  { id: 122, name: "Pikachu EX", set_name: "XY Promo", card_number: "XY84", rarity: "EX", release_year: 2015, price_eur: 32.86 },
  { id: 123, name: "Pikachu", set_name: "XY Promo", card_number: "XY89", rarity: "Promo", release_year: 2015, price_eur: 16.13 },
  { id: 124, name: "Poncho Wearing Pikachu (Mega Rayquaza)", set_name: "XY-P Promotional", card_number: "203/XY-P", rarity: "", release_year: 2015, price_eur: null },
  { id: 284, name: "Pikachu", set_name: "XY-P Promotional", card_number: "206/XY-P", rarity: "", release_year: 2015, price_eur: null },
  { id: 357, name: "Pikachu", set_name: "Miscellaneous Promos", card_number: "", rarity: "Promo", release_year: 2015, price_eur: null },
  { id: 366, name: "Pikachu", set_name: "League Promo", card_number: "", rarity: "Promo", release_year: 2015, price_eur: null },
  { id: 386, name: "Pikachu", set_name: "European Exclusive", card_number: "", rarity: "Promo", release_year: 2015, price_eur: null },
  { id: 125, name: "Mega Tokyo Pikachu", set_name: "XY-P Promotional", card_number: "204/XY-P", rarity: "", release_year: 2015, price_eur: null },
  { id: 285, name: "Pikachu", set_name: "XY-P Promotional", card_number: "210/XY-P", rarity: "", release_year: 2015, price_eur: null },
  { id: 126, name: "Poncho Wearing Pikachu (Mega Lucario)", set_name: "XY-P Promotional", card_number: "207/XY-P", rarity: "", release_year: 2015, price_eur: null },
  { id: 127, name: "Poncho Wearing Pikachu (Mega Slowbro)", set_name: "XY-P Promotional", card_number: "208/XY-P", rarity: "", release_year: 2015, price_eur: null },
  { id: 129, name: "Pikachu", set_name: "XY Promo", card_number: "XY95", rarity: "Promo", release_year: 2015, price_eur: 82.33 },
  { id: 286, name: "Pikachu", set_name: "XY-P Promotional", card_number: "220/XY-P", rarity: "", release_year: 2015, price_eur: null },
  { id: 298, name: "Pikachu", set_name: "XY-P Promotional", card_number: "XY-P", rarity: "", release_year: 2015, price_eur: null },
  { id: 358, name: "Pikachu", set_name: "Miscellaneous Promos", card_number: "", rarity: "Promo", release_year: 2015, price_eur: null },
  { id: 418, name: "Pikachu", set_name: "Premium Collection", card_number: "", rarity: "Promo", release_year: 2015, price_eur: null },
  { id: 128, name: "Pikachu", set_name: "BREAKthrough", card_number: "48/162", rarity: "Common", release_year: 2015, price_eur: 1.65 },
  { id: 130, name: "Okuge-Sama & Maiko-han Pikachu", set_name: "XY-P Promotional", card_number: "221/XY-P", rarity: "", release_year: 2015, price_eur: null },
  { id: 279, name: "Poncho Wearing Pikachu (Mega Sceptile)", set_name: "XY-P Promotional", card_number: "XY-P", rarity: "", release_year: 2015, price_eur: null },
  { id: 280, name: "Poncho Wearing Pikachu (Mega Blaziken)", set_name: "XY-P Promotional", card_number: "XY-P", rarity: "", release_year: 2015, price_eur: null },
  { id: 131, name: "McDonald\\'s 2016", set_name: "McDonald\\'s 2016", card_number: "6/12", rarity: "", release_year: 2016, price_eur: null },
  { id: 281, name: "Poncho Wearing Pikachu (Mega Swampert)", set_name: "XY-P Promotional", card_number: "XY-P", rarity: "", release_year: 2016, price_eur: null },
  { id: 372, name: "Pikachu", set_name: "Pokémon Center", card_number: "", rarity: "", release_year: 2016, price_eur: null },
  { id: 134, name: "Poncho Wearing Pikachu (Mega Charizard Y)", set_name: "XY-P Promotional", card_number: "230/XY-P", rarity: "", release_year: 2016, price_eur: null },
  { id: 135, name: "Poncho Wearing Pikachu (Mega Charizard X)", set_name: "XY-P Promotional", card_number: "231/XY-P", rarity: "", release_year: 2016, price_eur: null },
  { id: 359, name: "Pikachu", set_name: "Miscellaneous Promos", card_number: "", rarity: "Promo", release_year: 2016, price_eur: null },
  { id: 409, name: "Pikachu JUMBO", set_name: "Jumbo Promo", card_number: "", rarity: "Jumbo", release_year: 2016, price_eur: null },
  { id: 428, name: "Pikachu", set_name: "20th Anniversary", card_number: "", rarity: "Promo", release_year: 2016, price_eur: null },
  { id: 132, name: "Pikachu", set_name: "Generations", card_number: "26/83", rarity: "Common", release_year: 2016, price_eur: 3.6 },
  { id: 133, name: "Pikachu", set_name: "Generations", card_number: "RC29/RC32", rarity: "Radiant", release_year: 2016, price_eur: 59.91 },
  { id: 136, name: "Pikachu Libre", set_name: "XY-P Promotional", card_number: "247/XY-P", rarity: "", release_year: 2016, price_eur: null },
  { id: 299, name: "Pikachu", set_name: "XY-P Promotional", card_number: "XY-P", rarity: "", release_year: 2016, price_eur: null },
  { id: 137, name: "Pikachu", set_name: "XY-P Promotional", card_number: "259/XY-P", rarity: "", release_year: 2016, price_eur: null },
  { id: 287, name: "Pikachu", set_name: "XY-P Promotional", card_number: "260/XY-P", rarity: "", release_year: 2016, price_eur: null },
  { id: 393, name: "Pikachu", set_name: "TCG Online", card_number: "", rarity: "Digital", release_year: 2016, price_eur: null },
  { id: 138, name: "Poncho Wearing Pikachu (Mega Gyarados)", set_name: "XY-P Promotional", card_number: "274/XY-P", rarity: "", release_year: 2016, price_eur: null },
  { id: 139, name: "Poncho Wearing Pikachu (Mega Altaria)", set_name: "XY-P Promotional", card_number: "275/XY-P", rarity: "", release_year: 2016, price_eur: null },
  { id: 387, name: "Pikachu", set_name: "European Exclusive", card_number: "", rarity: "Promo", release_year: 2016, price_eur: null },
  { id: 140, name: "Pikachu", set_name: "XY-P Promotional", card_number: "279/XY-P", rarity: "", release_year: 2016, price_eur: null },
  { id: 367, name: "Pikachu", set_name: "League Promo", card_number: "", rarity: "Promo", release_year: 2016, price_eur: null },
  { id: 141, name: "Pikachu", set_name: "XY-P Promotional", card_number: "281/XY-P", rarity: "", release_year: 2016, price_eur: null },
  { id: 288, name: "Pikachu", set_name: "XY-P Promotional", card_number: "280/XY-P", rarity: "", release_year: 2016, price_eur: null },
  { id: 404, name: "Pikachu", set_name: "Movie Promo", card_number: "", rarity: "Promo", release_year: 2016, price_eur: null },
  { id: 425, name: "Pikachu", set_name: "Deck Kit", card_number: "", rarity: "", release_year: 2016, price_eur: null },
  { id: 289, name: "Pikachu", set_name: "XY-P Promotional", card_number: "290/XY-P", rarity: "", release_year: 2016, price_eur: null },
  { id: 337, name: "Pikachu", set_name: "World Championship 2016", card_number: "", rarity: "Promo", release_year: 2016, price_eur: null },
  { id: 142, name: "Mario Pikachu", set_name: "XY-P Promotional", card_number: "293/XY-P", rarity: "", release_year: 2016, price_eur: null },
  { id: 143, name: "Mario Pikachu (full art)", set_name: "XY-P Promotional", card_number: "294/XY-P", rarity: "", release_year: 2016, price_eur: null },
  { id: 144, name: "Luigi Pikachu", set_name: "XY-P Promotional", card_number: "295/XY-P", rarity: "", release_year: 2016, price_eur: null },
  { id: 145, name: "Luigi Pikachu (full art)", set_name: "XY-P Promotional", card_number: "296/XY-P", rarity: "", release_year: 2016, price_eur: null },
  { id: 451, name: "Pikachu", set_name: "Store Championship", card_number: "", rarity: "Promo", release_year: 2016, price_eur: null },
  { id: 419, name: "Pikachu EX", set_name: "Premium Collection", card_number: "", rarity: "Promo", release_year: 2016, price_eur: null },
  { id: 149, name: "Pikachu EX", set_name: "XY Promo", card_number: "XY124", rarity: "EX", release_year: 2016, price_eur: 112.17 },
  { id: 360, name: "Pikachu", set_name: "Miscellaneous Promos", card_number: "", rarity: "Promo", release_year: 2016, price_eur: null },
  { id: 410, name: "Pikachu EX JUMBO", set_name: "Jumbo Promo", card_number: "", rarity: "Jumbo", release_year: 2016, price_eur: null },
  { id: 146, name: "Pikachu", set_name: "Evolutions", card_number: "35/108", rarity: "Common", release_year: 2016, price_eur: 2.22 },
  { id: 147, name: "Flying Pikachu", set_name: "Evolutions", card_number: "110/108", rarity: "Secret", release_year: 2016, price_eur: 5.88 },
  { id: 148, name: "Surfing Pikachu", set_name: "Evolutions", card_number: "111/108", rarity: "Secret", release_year: 2016, price_eur: 4.82 },
  { id: 150, name: "Pikachu EX", set_name: "XY Promo", card_number: "XY174", rarity: "EX", release_year: 2016, price_eur: 10.51 },
  { id: 151, name: "Pikachu", set_name: "XY Promo", card_number: "XY202", rarity: "Promo", release_year: 2016, price_eur: 21.76 },
  { id: 152, name: "Pikachu", set_name: "Pikachu\\'s New Friends", card_number: "004/004", rarity: "", release_year: 2016, price_eur: null },
  { id: 300, name: "Pikachu", set_name: "SM-P Promotional", card_number: "001/SM-P", rarity: "", release_year: 2016, price_eur: null },
  { id: 301, name: "Pikachu", set_name: "SM-P Promotional", card_number: "002/SM-P", rarity: "", release_year: 2017, price_eur: null },
  { id: 453, name: "Pikachu", set_name: "Regional Championship", card_number: "", rarity: "Promo", release_year: 2017, price_eur: null },
  { id: 153, name: "Pikachu", set_name: "SM Promo", card_number: "SM04", rarity: "Promo", release_year: 2017, price_eur: 30.72 },
  { id: 445, name: "Pikachu", set_name: "Theme Deck", card_number: "", rarity: "", release_year: 2017, price_eur: null },
  { id: 154, name: "McDonald\\'s 2017", set_name: "McDonald\\'s 2017", card_number: "5/12", rarity: "", release_year: 2017, price_eur: null },
  { id: 155, name: "Pikachu", set_name: "SM-P Promotional", card_number: "001/SM-P", rarity: "", release_year: 2017, price_eur: null },
  { id: 156, name: "Pikachu", set_name: "SM-P Promotional", card_number: "004/SM-P", rarity: "", release_year: 2017, price_eur: null },
  { id: 157, name: "Pikachu", set_name: "SM-P Promotional", card_number: "009/SM-P", rarity: "", release_year: 2017, price_eur: null },
  { id: 373, name: "Pikachu", set_name: "Pokémon Center", card_number: "", rarity: "", release_year: 2017, price_eur: null },
  { id: 390, name: "Pikachu", set_name: "Latin America Promo", card_number: "", rarity: "", release_year: 2017, price_eur: null },
  { id: 320, name: "Pikachu", set_name: "Korean SM-P Promos", card_number: "002/SM-P", rarity: "", release_year: 2017, price_eur: null },
  { id: 325, name: "Pikachu", set_name: "Chinese SM-P Promos", card_number: "003/SM-P", rarity: "", release_year: 2017, price_eur: null },
  { id: 361, name: "Pikachu", set_name: "Miscellaneous Promos", card_number: "", rarity: "Promo", release_year: 2017, price_eur: null },
  { id: 158, name: "Pikachu", set_name: "Alolan Raichu Half Deck", card_number: "14/30", rarity: "", release_year: 2017, price_eur: null },
  { id: 159, name: "Pikachu", set_name: "Alolan Raichu Half Deck", card_number: "29/30", rarity: "", release_year: 2017, price_eur: null },
  { id: 302, name: "Pikachu", set_name: "SM-P Promotional", card_number: "061/SM-P", rarity: "", release_year: 2017, price_eur: null },
  { id: 321, name: "Pikachu", set_name: "Korean SM-P Promos", card_number: "010/SM-P", rarity: "", release_year: 2017, price_eur: null },
  { id: 329, name: "Pikachu", set_name: "Thai SM-P Promos", card_number: "005/SM-P", rarity: "", release_year: 2017, price_eur: null },
  { id: 394, name: "Pikachu", set_name: "TCG Online", card_number: "", rarity: "Digital", release_year: 2017, price_eur: null },
  { id: 160, name: "Pikachu", set_name: "SM Promo", card_number: "SM76", rarity: "Promo", release_year: 2017, price_eur: 7.82 },
  { id: 303, name: "Pikachu", set_name: "SM-P Promotional", card_number: "068/SM-P", rarity: "", release_year: 2017, price_eur: null },
  { id: 332, name: "Pikachu", set_name: "Indonesian SM-P Promos", card_number: "010/SM-P", rarity: "", release_year: 2017, price_eur: null },
  { id: 405, name: "Pikachu", set_name: "Movie Promo", card_number: "", rarity: "Promo", release_year: 2017, price_eur: null },
  { id: 431, name: "Pikachu", set_name: "Build-A-Bear", card_number: "", rarity: "Promo", release_year: 2017, price_eur: null },
  { id: 161, name: "Pikachu", set_name: "SM Promo", card_number: "SM81", rarity: "Promo", release_year: 2017, price_eur: 11.02 },
  { id: 326, name: "Pikachu", set_name: "Chinese SM-P Promos", card_number: "015/SM-P", rarity: "", release_year: 2017, price_eur: null },
  { id: 338, name: "Pikachu", set_name: "World Championship 2017", card_number: "", rarity: "Promo", release_year: 2017, price_eur: null },
  { id: 388, name: "Pikachu", set_name: "European Exclusive", card_number: "", rarity: "Promo", release_year: 2017, price_eur: null },
  { id: 164, name: "Pikachu", set_name: "Burning Shadows", card_number: "40/147", rarity: "Common", release_year: 2017, price_eur: 0.49 },
  { id: 162, name: "Pikachu", set_name: "SM Promo", card_number: "SM86", rarity: "Promo", release_year: 2017, price_eur: 22.72 },
  { id: 163, name: "Pikachu", set_name: "SM-P Promotional", card_number: "179/SM-P", rarity: "", release_year: 2017, price_eur: null },
  { id: 165, name: "Pikachu", set_name: "SM-P Promotional", card_number: "108/SM-P", rarity: "", release_year: 2017, price_eur: null },
  { id: 304, name: "Pikachu", set_name: "SM-P Promotional", card_number: "100/SM-P", rarity: "", release_year: 2017, price_eur: null },
  { id: 322, name: "Pikachu", set_name: "Korean SM-P Promos", card_number: "020/SM-P", rarity: "", release_year: 2017, price_eur: null },
  { id: 172, name: "Pikachu", set_name: "GX Battle Boost", card_number: "028/114", rarity: "", release_year: 2017, price_eur: null },
  { id: 305, name: "Pikachu", set_name: "SM-P Promotional", card_number: "109/SM-P", rarity: "", release_year: 2017, price_eur: null },
  { id: 168, name: "Pikachu", set_name: "Shining Legends", card_number: "28/73", rarity: "Common", release_year: 2017, price_eur: 2.33 },
  { id: 166, name: "Pikachu", set_name: "SM Promo", card_number: "SM98", rarity: "Promo", release_year: 2017, price_eur: 45.49 },
  { id: 167, name: "Ash\\'s Pikachu-GX", set_name: "Ash vs Team Rocket", card_number: "5/26", rarity: "GX", release_year: 2017, price_eur: null },
  { id: 173, name: "Pikachu", set_name: "SM-P Promotional", card_number: "168/SM-P", rarity: "", release_year: 2017, price_eur: null },
  { id: 171, name: "Pikachu", set_name: "Crimson Invasion", card_number: "30/111", rarity: "Common", release_year: 2017, price_eur: 1.04 },
  { id: 169, name: "Pikachu", set_name: "Lightning Raichu-GX Deck", card_number: "032/131", rarity: "", release_year: 2017, price_eur: null },
  { id: 330, name: "Pikachu", set_name: "Thai SM-P Promos", card_number: "012/SM-P", rarity: "", release_year: 2017, price_eur: null },
  { id: 368, name: "Pikachu", set_name: "League Promo", card_number: "", rarity: "Promo", release_year: 2017, price_eur: null },
  { id: 323, name: "Pikachu", set_name: "Korean SM-P Promos", card_number: "030/SM-P", rarity: "", release_year: 2018, price_eur: null },
  { id: 327, name: "Pikachu", set_name: "Chinese SM-P Promos", card_number: "025/SM-P", rarity: "", release_year: 2018, price_eur: null },
  { id: 362, name: "Pikachu", set_name: "Miscellaneous Promos", card_number: "", rarity: "Promo", release_year: 2018, price_eur: null },
  { id: 170, name: "McDonald\\'s 2018", set_name: "McDonald\\'s 2018", card_number: "4/12", rarity: "", release_year: 2018, price_eur: null },
  { id: 174, name: "Pikachu", set_name: "SM-P Promotional", card_number: "199/SM-P", rarity: "", release_year: 2018, price_eur: null },
  { id: 306, name: "Pikachu", set_name: "SM-P Promotional", card_number: "150/SM-P", rarity: "", release_year: 2018, price_eur: null },
  { id: 175, name: "Pikachu", set_name: "SM-P Promotional", card_number: "200/SM-P", rarity: "", release_year: 2018, price_eur: null },
  { id: 176, name: "Pikachu", set_name: "SM-P Promotional", card_number: "207/SM-P", rarity: "", release_year: 2018, price_eur: null },
  { id: 177, name: "Ash\\'s Pikachu (Original)", set_name: "SM Promo", card_number: "SM108", rarity: "Promo", release_year: 2018, price_eur: 26.66 },
  { id: 178, name: "Ash\\'s Pikachu (Hoenn)", set_name: "SM Promo", card_number: "SM109", rarity: "Promo", release_year: 2018, price_eur: 21.7 },
  { id: 179, name: "Ash\\'s Pikachu (Sinnoh)", set_name: "SM Promo", card_number: "SM110", rarity: "Promo", release_year: 2018, price_eur: 22.34 },
  { id: 180, name: "Ash\\'s Pikachu (Unova)", set_name: "SM Promo", card_number: "SM111", rarity: "Promo", release_year: 2018, price_eur: 21.05 },
  { id: 181, name: "Ash\\'s Pikachu (Kalos)", set_name: "SM Promo", card_number: "SM112", rarity: "Promo", release_year: 2018, price_eur: 22.03 },
  { id: 182, name: "Ash\\'s Pikachu (Alola)", set_name: "SM Promo", card_number: "SM113", rarity: "Promo", release_year: 2018, price_eur: 20.84 },
  { id: 183, name: "Ash\\'s Pikachu (World)", set_name: "SM Promo", card_number: "SM114", rarity: "Promo", release_year: 2018, price_eur: 13.98 },
  { id: 331, name: "Pikachu", set_name: "Thai SM-P Promos", card_number: "018/SM-P", rarity: "", release_year: 2018, price_eur: null },
  { id: 411, name: "Pikachu-GX JUMBO", set_name: "Jumbo Promo", card_number: "", rarity: "Jumbo", release_year: 2018, price_eur: null },
  { id: 307, name: "Pikachu", set_name: "SM-P Promotional", card_number: "180/SM-P", rarity: "", release_year: 2018, price_eur: null },
  { id: 324, name: "Pikachu", set_name: "Korean SM-P Promos", card_number: "040/SM-P", rarity: "", release_year: 2018, price_eur: null },
  { id: 452, name: "Pikachu", set_name: "Store Championship", card_number: "", rarity: "Promo", release_year: 2018, price_eur: null },
  { id: 374, name: "Pikachu", set_name: "Pokémon Center", card_number: "", rarity: "", release_year: 2018, price_eur: null },
  { id: 391, name: "Pikachu", set_name: "Latin America Promo", card_number: "", rarity: "", release_year: 2018, price_eur: null },
  { id: 406, name: "Pikachu", set_name: "Movie Promo", card_number: "", rarity: "Promo", release_year: 2018, price_eur: null },
  { id: 184, name: "Pikachu", set_name: "SM Promo", card_number: "SM157", rarity: "Promo", release_year: 2018, price_eur: 14.22 },
  { id: 328, name: "Pikachu", set_name: "Chinese SM-P Promos", card_number: "035/SM-P", rarity: "", release_year: 2018, price_eur: null },
  { id: 333, name: "Pikachu", set_name: "Indonesian SM-P Promos", card_number: "020/SM-P", rarity: "", release_year: 2018, price_eur: null },
  { id: 339, name: "Pikachu", set_name: "World Championship 2018", card_number: "", rarity: "Promo", release_year: 2018, price_eur: null },
  { id: 185, name: "Pikachu", set_name: "SM Promo", card_number: "SM162", rarity: "Promo", release_year: 2018, price_eur: 87.12 },
  { id: 308, name: "Pikachu", set_name: "SM-P Promotional", card_number: "208/SM-P", rarity: "", release_year: 2018, price_eur: null },
  { id: 189, name: "Pikachu", set_name: "SM-P Promotional", card_number: "224/SM-P", rarity: "", release_year: 2018, price_eur: null },
  { id: 191, name: "Pikachu", set_name: "SM Promo", card_number: "SM168", rarity: "Promo", release_year: 2018, price_eur: 151.59 },
  { id: 309, name: "Pikachu", set_name: "SM-P Promotional", card_number: "225/SM-P", rarity: "", release_year: 2018, price_eur: null },
  { id: 389, name: "Pikachu", set_name: "European Exclusive", card_number: "", rarity: "Promo", release_year: 2018, price_eur: null },
  { id: 420, name: "Pikachu-GX", set_name: "Premium Collection", card_number: "", rarity: "Promo", release_year: 2018, price_eur: null },
  { id: 190, name: "Pikachu", set_name: "SM-P Promotional", card_number: "227/SM-P", rarity: "", release_year: 2018, price_eur: null },
  { id: 395, name: "Pikachu", set_name: "TCG Online", card_number: "", rarity: "Digital", release_year: 2018, price_eur: null },
  { id: 375, name: "Pikachu", set_name: "Pokémon Center", card_number: "", rarity: "", release_year: 2019, price_eur: null },
  { id: 412, name: "Pikachu & Zekrom-GX JUMBO", set_name: "Jumbo Promo", card_number: "", rarity: "Jumbo", release_year: 2019, price_eur: null },
  { id: 464, name: "Pretend Tea Ceremony Pikachu", set_name: "SM-P Promotional", card_number: "325/SM-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 186, name: "Pikachu & Zekrom-GX", set_name: "Team Up", card_number: "33/181", rarity: "GX", release_year: 2019, price_eur: 47.17 },
  { id: 187, name: "Pikachu & Zekrom-GX (Full Art)", set_name: "Team Up", card_number: "162/181", rarity: "GX", release_year: 2019, price_eur: 121.82 },
  { id: 188, name: "Pikachu & Zekrom-GX (Rainbow)", set_name: "Team Up", card_number: "184/181", rarity: "GX", release_year: 2019, price_eur: 97.35 },
  { id: 193, name: "Detective Pikachu", set_name: "SM Promo", card_number: "SM170", rarity: "Promo", release_year: 2019, price_eur: 72.75 },
  { id: 196, name: "McDonald\\'s 2019", set_name: "McDonald\\'s 2019", card_number: "6/12", rarity: "", release_year: 2019, price_eur: null },
  { id: 197, name: "Pikachu", set_name: "SM-P Promotional", card_number: "249/SM-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 310, name: "Pikachu", set_name: "SM-P Promotional", card_number: "250/SM-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 194, name: "Detective Pikachu", set_name: "SM Promo", card_number: "SM190", rarity: "Promo", release_year: 2019, price_eur: 9.63 },
  { id: 195, name: "Detective Pikachu", set_name: "SM Promo", card_number: "SM194", rarity: "Promo", release_year: 2019, price_eur: 7.16 },
  { id: 198, name: "Pikachu", set_name: "SM-P Promotional", card_number: "262/SM-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 311, name: "Pikachu", set_name: "SM-P Promotional", card_number: "263/SM-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 192, name: "Detective Pikachu", set_name: "Detective Pikachu", card_number: "10/18", rarity: "Holo", release_year: 2019, price_eur: 17.5 },
  { id: 199, name: "Pikachu", set_name: "SM-P Promotional", card_number: "276/SM-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 312, name: "Pikachu", set_name: "SM-P Promotional", card_number: "277/SM-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 363, name: "Pikachu", set_name: "Miscellaneous Promos", card_number: "", rarity: "Promo", release_year: 2019, price_eur: null },
  { id: 454, name: "Pikachu", set_name: "Regional Championship", card_number: "", rarity: "Promo", release_year: 2019, price_eur: null },
  { id: 516, name: "Detective Pikachu", set_name: "Indonesia Promo", card_number: "", rarity: "Promo", release_year: 2019, price_eur: null },
  { id: 200, name: "Pikachu", set_name: "Unbroken Bonds", card_number: "54/214", rarity: "Common", release_year: 2019, price_eur: 2.54 },
  { id: 202, name: "Pikachu", set_name: "SM-P Promotional", card_number: "288/SM-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 313, name: "Pikachu", set_name: "SM-P Promotional", card_number: "289/SM-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 201, name: "Pikachu", set_name: "S-P Promotional", card_number: "125/S-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 203, name: "Pikachu", set_name: "SM-P Promotional", card_number: "291/SM-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 314, name: "Pikachu", set_name: "SM-P Promotional", card_number: "300/SM-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 207, name: "Pikachu", set_name: "SM Promo", card_number: "SM183", rarity: "Promo", release_year: 2019, price_eur: 11.02 },
  { id: 208, name: "Pikachu", set_name: "SM-P Promotional", card_number: "307/SM-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 315, name: "Pikachu", set_name: "SM-P Promotional", card_number: "320/SM-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 340, name: "Pikachu", set_name: "World Championship 2019", card_number: "", rarity: "Promo", release_year: 2019, price_eur: null },
  { id: 204, name: "Pikachu", set_name: "Unified Minds", card_number: "55/236", rarity: "Common", release_year: 2019, price_eur: 1.3 },
  { id: 205, name: "Pikachu", set_name: "Unified Minds", card_number: "56/236", rarity: "Common", release_year: 2019, price_eur: 4.39 },
  { id: 206, name: "Pikachu", set_name: "Hidden Fates", card_number: "19/68", rarity: "Common", release_year: 2019, price_eur: 0.62 },
  { id: 209, name: "Pikachu", set_name: "SM Promo", card_number: "SM206", rarity: "Promo", release_year: 2019, price_eur: 14.74 },
  { id: 210, name: "Pikachu", set_name: "SM Promo", card_number: "SM227", rarity: "Promo", release_year: 2019, price_eur: 14.55 },
  { id: 251, name: "Shibuya\\'s Pikachu", set_name: "S-P Promotional", card_number: "002/S-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 316, name: "Pikachu", set_name: "SM-P Promotional", card_number: "350/SM-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 343, name: "Pikachu", set_name: "S-P Promotional", card_number: "002/S-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 211, name: "Pikachu", set_name: "SM-P Promotional", card_number: "369/SM-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 212, name: "Pikachu", set_name: "SM-P Promotional", card_number: "376/SM-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 213, name: "Pikachu", set_name: "SM-P Promotional", card_number: "377/SM-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 317, name: "Pikachu", set_name: "SM-P Promotional", card_number: "368/SM-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 392, name: "Pikachu", set_name: "Latin America Promo", card_number: "", rarity: "", release_year: 2019, price_eur: null },
  { id: 426, name: "Pikachu", set_name: "Deck Kit", card_number: "", rarity: "", release_year: 2019, price_eur: null },
  { id: 446, name: "Pikachu", set_name: "Theme Deck", card_number: "", rarity: "", release_year: 2019, price_eur: null },
  { id: 215, name: "Pikachu", set_name: "Cosmic Eclipse", card_number: "66/236", rarity: "Common", release_year: 2019, price_eur: 1.4 },
  { id: 216, name: "Pikachu (Character Rare)", set_name: "Cosmic Eclipse", card_number: "241/236", rarity: "CHR", release_year: 2019, price_eur: 71.73 },
  { id: 214, name: "Pikachu", set_name: "SM-P Promotional", card_number: "400/SM-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 217, name: "Pikachu", set_name: "S-P Promotional", card_number: "126/S-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 218, name: "Pikachu", set_name: "SM Promo", card_number: "SM234", rarity: "Promo", release_year: 2019, price_eur: 18.23 },
  { id: 318, name: "Pikachu", set_name: "SM-P Promotional", card_number: "380/SM-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 319, name: "Pikachu", set_name: "SM-P Promotional", card_number: "390/SM-P", rarity: "", release_year: 2019, price_eur: null },
  { id: 376, name: "Pikachu", set_name: "Pokémon Center", card_number: "", rarity: "", release_year: 2020, price_eur: null },
  { id: 220, name: "Pikachu", set_name: "25th Anniversary Golden Box", card_number: "003/015", rarity: "", release_year: 2020, price_eur: null },
  { id: 221, name: "Pikachu", set_name: "SWSH Promo", card_number: "SWSH020", rarity: "Promo", release_year: 2020, price_eur: 60.23 },
  { id: 435, name: "Pikachu", set_name: "McDonald\\'s 2020", card_number: "", rarity: "", release_year: 2020, price_eur: null },
  { id: 436, name: "Pikachu", set_name: "McDonald\\'s 2020", card_number: "", rarity: "", release_year: 2020, price_eur: null },
  { id: 219, name: "Pikachu", set_name: "Sword & Shield", card_number: "65/202", rarity: "Common", release_year: 2020, price_eur: 0.63 },
  { id: 252, name: "Rescue Team DX\\'s Pikachu", set_name: "S-P Promotional", card_number: "036/S-P", rarity: "", release_year: 2020, price_eur: null },
  { id: 344, name: "Pikachu", set_name: "S-P Promotional", card_number: "036/S-P", rarity: "", release_year: 2020, price_eur: null },
  { id: 437, name: "Pikachu", set_name: "McDonald\\'s 2020", card_number: "", rarity: "", release_year: 2020, price_eur: null },
  { id: 438, name: "Pikachu", set_name: "McDonald\\'s 2020", card_number: "", rarity: "", release_year: 2020, price_eur: null },
  { id: 222, name: "Pikachu", set_name: "SWSH Promo", card_number: "SWSH039", rarity: "Promo", release_year: 2020, price_eur: 9.1 },
  { id: 345, name: "Pikachu", set_name: "S-P Promotional", card_number: "050/S-P", rarity: "", release_year: 2020, price_eur: null },
  { id: 253, name: "Detective Pikachu", set_name: "S-P Promotional", card_number: "099/S-P", rarity: "", release_year: 2020, price_eur: null },
  { id: 347, name: "Pikachu", set_name: "S-P Promotional", card_number: "099/S-P", rarity: "", release_year: 2020, price_eur: null },
  { id: 447, name: "Pikachu", set_name: "Battle Academy", card_number: "", rarity: "", release_year: 2020, price_eur: null },
  { id: 223, name: "Pikachu", set_name: "S-P Promotional", card_number: "132/S-P", rarity: "", release_year: 2020, price_eur: null },
  { id: 254, name: "Swallowed Pikachu", set_name: "S-P Promotional", card_number: "105/S-P", rarity: "", release_year: 2020, price_eur: null },
  { id: 346, name: "Pikachu", set_name: "S-P Promotional", card_number: "075/S-P", rarity: "", release_year: 2020, price_eur: null },
  { id: 348, name: "Pikachu", set_name: "S-P Promotional", card_number: "105/S-P", rarity: "", release_year: 2020, price_eur: null },
  { id: 407, name: "Pikachu", set_name: "Movie Promo", card_number: "", rarity: "Promo", release_year: 2020, price_eur: null },
  { id: 224, name: "Pikachu", set_name: "7 Illustrators", card_number: "006/007", rarity: "", release_year: 2020, price_eur: null },
  { id: 467, name: "Pikachu V", set_name: "SWSH Promo", card_number: "SWSH063", rarity: "Promo", release_year: 2020, price_eur: 6.68 },
  { id: 421, name: "Pikachu V", set_name: "Premium Collection", card_number: "", rarity: "Promo", release_year: 2020, price_eur: null },
  { id: 255, name: "Kanazawa\\'s Pikachu", set_name: "S-P Promotional", card_number: "144/S-P", rarity: "", release_year: 2020, price_eur: null },
  { id: 349, name: "Pikachu", set_name: "S-P Promotional", card_number: "144/S-P", rarity: "", release_year: 2020, price_eur: null },
  { id: 413, name: "Pikachu VMAX JUMBO", set_name: "Jumbo Promo", card_number: "", rarity: "Jumbo", release_year: 2020, price_eur: null },
  { id: 514, name: "Special Delivery Pikachu", set_name: "SWSH Black Star Promos", card_number: "SWSH076", rarity: "Promo", release_year: 2020, price_eur: null },
  { id: 535, name: "Pikachu V", set_name: "Vivid Voltage", card_number: "43/185", rarity: "Ultra Rare", release_year: 2020, price_eur: 4.51 },
  { id: 536, name: "Pikachu VMAX", set_name: "Vivid Voltage", card_number: "44/185", rarity: "Ultra Rare", release_year: 2020, price_eur: 6.05 },
  { id: 350, name: "Pikachu", set_name: "S-P Promotional", card_number: "150/S-P", rarity: "", release_year: 2020, price_eur: null },
  { id: 230, name: "McDonald\\'s 2021", set_name: "McDonald\\'s 2021", card_number: "25/25", rarity: "", release_year: 2021, price_eur: null },
  { id: 468, name: "Pikachu V", set_name: "SWSH Promo", card_number: "SWSH090", rarity: "Promo", release_year: 2021, price_eur: null },
  { id: 351, name: "Pikachu", set_name: "S-P Promotional", card_number: "175/S-P", rarity: "", release_year: 2021, price_eur: null },
  { id: 422, name: "Pikachu VMAX", set_name: "Premium Collection", card_number: "", rarity: "Promo", release_year: 2021, price_eur: null },
  { id: 432, name: "Pikachu", set_name: "Build-A-Bear", card_number: "", rarity: "Promo", release_year: 2021, price_eur: null },
  { id: 538, name: "Pikachu", set_name: "SWSH Black Star Promos", card_number: "SWSH039", rarity: "Promo", release_year: 2021, price_eur: 9.1 },
  { id: 227, name: "Pikachu", set_name: "S-P Promotional", card_number: "208/S-P", rarity: "", release_year: 2021, price_eur: null },
  { id: 256, name: "Picture Pikachu", set_name: "S-P Promotional", card_number: "208/S-P", rarity: "", release_year: 2021, price_eur: null },
  { id: 352, name: "Pikachu", set_name: "S-P Promotional", card_number: "200/S-P", rarity: "", release_year: 2021, price_eur: null },
  { id: 228, name: "Pikachu", set_name: "S-P Promotional", card_number: "227/S-P", rarity: "", release_year: 2021, price_eur: null },
  { id: 448, name: "Pikachu", set_name: "Battle Academy", card_number: "", rarity: "", release_year: 2021, price_eur: null },
  { id: 539, name: "Pikachu", set_name: "SWSH Black Star Promos", card_number: "SWSH061", rarity: "Promo", release_year: 2021, price_eur: 1.29 },
  { id: 334, name: "Pikachu", set_name: "Indonesian SM-P Promos", card_number: "240/S-P", rarity: "", release_year: 2021, price_eur: null },
  { id: 469, name: "Pikachu VMAX", set_name: "SWSH Promo", card_number: "SWSH123", rarity: "Promo", release_year: 2021, price_eur: null },
  { id: 225, name: "Pikachu", set_name: "Evolving Skies", card_number: "49/203", rarity: "Common", release_year: 2021, price_eur: 0.15 },
  { id: 353, name: "Pikachu", set_name: "S-P Promotional", card_number: "230/S-P", rarity: "", release_year: 2021, price_eur: null },
  { id: 429, name: "Pikachu", set_name: "25th Anniversary", card_number: "", rarity: "Holo", release_year: 2021, price_eur: null },
  { id: 229, name: "Pikachu", set_name: "Celebrations", card_number: "5/25", rarity: "", release_year: 2021, price_eur: 4.11 },
  { id: 531, name: "Flying Pikachu V", set_name: "Celebrations", card_number: "6/25", rarity: "Promo", release_year: 2021, price_eur: 2.9 },
  { id: 532, name: "Flying Pikachu VMAX", set_name: "Celebrations", card_number: "7/25", rarity: "Promo", release_year: 2021, price_eur: 5 },
  { id: 533, name: "Surfing Pikachu V", set_name: "Celebrations", card_number: "8/25", rarity: "Promo", release_year: 2021, price_eur: 3.51 },
  { id: 534, name: "Surfing Pikachu VMAX", set_name: "Celebrations", card_number: "9/25", rarity: "Promo", release_year: 2021, price_eur: 6.47 },
  { id: 540, name: "Pikachu V-UNION", set_name: "SWSH Black Star Promos", card_number: "SWSH139", rarity: "Promo", release_year: 2021, price_eur: 6.9 },
  { id: 541, name: "Pikachu V-UNION", set_name: "SWSH Black Star Promos", card_number: "SWSH140", rarity: "Promo", release_year: 2021, price_eur: 5.01 },
  { id: 542, name: "Pikachu V-UNION", set_name: "SWSH Black Star Promos", card_number: "SWSH141", rarity: "Promo", release_year: 2021, price_eur: 4.84 },
  { id: 543, name: "Pikachu V-UNION", set_name: "SWSH Black Star Promos", card_number: "SWSH142", rarity: "Promo", release_year: 2021, price_eur: 5.25 },
  { id: 258, name: "McDonald\\'s Pikachu", set_name: "M-P Promotional", card_number: "020/M-P", rarity: "", release_year: 2021, price_eur: null },
  { id: 537, name: "Pikachu V", set_name: "Fusion Strike", card_number: "86/264", rarity: "Ultra Rare", release_year: 2021, price_eur: 1.74 },
  { id: 226, name: "Pikachu", set_name: "Start Deck 100", card_number: "127/414", rarity: "", release_year: 2021, price_eur: null },
  { id: 354, name: "Pikachu", set_name: "S-P Promotional", card_number: "250/S-P", rarity: "", release_year: 2021, price_eur: null },
  { id: 257, name: "Pikachu VMAX (Gigantamax)", set_name: "S-P Promotional", card_number: "265/S-P", rarity: "VMAX", release_year: 2022, price_eur: null },
  { id: 471, name: "Pikachu", set_name: "Brilliant Stars", card_number: "74/172", rarity: "Common", release_year: 2022, price_eur: null },
  { id: 472, name: "Pikachu (TG)", set_name: "Brilliant Stars", card_number: "TG7/TG30", rarity: "", release_year: 2022, price_eur: null },
  { id: 234, name: "Pikachu VMAX", set_name: "SWSH Promo", card_number: "SWSH174", rarity: "VMAX", release_year: 2022, price_eur: null },
  { id: 235, name: "Pikachu V", set_name: "SWSH Promo", card_number: "SWSH175", rarity: "V", release_year: 2022, price_eur: null },
  { id: 355, name: "Pikachu", set_name: "S-P Promotional", card_number: "275/S-P", rarity: "", release_year: 2022, price_eur: null },
  { id: 470, name: "Pikachu V", set_name: "SWSH Promo", card_number: "SWSH175", rarity: "Promo", release_year: 2022, price_eur: null },
  { id: 473, name: "Pikachu", set_name: "Astral Radiance", card_number: "53/189", rarity: "Common", release_year: 2022, price_eur: null },
  { id: 356, name: "Pikachu", set_name: "S-P Promotional", card_number: "300/S-P", rarity: "", release_year: 2022, price_eur: null },
  { id: 442, name: "Pikachu", set_name: "Pokémon GO Fest", card_number: "", rarity: "Promo", release_year: 2022, price_eur: null },
  { id: 544, name: "Pikachu", set_name: "SWSH Black Star Promos", card_number: "SWSH198", rarity: "Promo", release_year: 2022, price_eur: 1.4 },
  { id: 474, name: "Radiant Pikachu", set_name: "Pokémon GO", card_number: "86/78", rarity: "Radiant", release_year: 2022, price_eur: null },
  { id: 231, name: "Pikachu", set_name: "Pokémon GO", card_number: "27/78", rarity: "Common", release_year: 2022, price_eur: 0.1 },
  { id: 232, name: "Pikachu", set_name: "Pokémon GO", card_number: "28/78", rarity: "Common", release_year: 2022, price_eur: 0.44 },
  { id: 233, name: "McDonald\\'s 2022", set_name: "McDonald\\'s 2022", card_number: "7/15", rarity: "", release_year: 2022, price_eur: null },
  { id: 341, name: "Pikachu", set_name: "World Championship 2022", card_number: "", rarity: "Promo", release_year: 2022, price_eur: null },
  { id: 465, name: "Boss and Pikachu", set_name: "Yokohama Promo", card_number: "", rarity: "", release_year: 2022, price_eur: null },
  { id: 456, name: "Pikachu V (TG)", set_name: "Lost Origin", card_number: "TG5/TG30", rarity: "V", release_year: 2022, price_eur: null },
  { id: 457, name: "Pikachu VMAX (TG)", set_name: "Lost Origin", card_number: "TG17/TG30", rarity: "VMAX", release_year: 2022, price_eur: 79.38 },
  { id: 475, name: "Pikachu", set_name: "Lost Origin", card_number: "52/196", rarity: "Common", release_year: 2022, price_eur: 0.08 },
  { id: 476, name: "Pikachu VMAX (alt)", set_name: "Lost Origin", card_number: "TG29/TG30", rarity: "VMAX", release_year: 2022, price_eur: 13.77 },
  { id: 249, name: "Pikachu VMAX", set_name: "Lost Origin", card_number: "TG16/TG30", rarity: "VMAX", release_year: 2022, price_eur: 108.76 },
  { id: 250, name: "Pikachu V", set_name: "Lost Origin", card_number: "TG5/TG30", rarity: "V", release_year: 2022, price_eur: null },
  { id: 455, name: "Pikachu", set_name: "Regional Championship", card_number: "", rarity: "Promo", release_year: 2022, price_eur: null },
  { id: 459, name: "Pikachu", set_name: "Silver Tempest", card_number: "49/195", rarity: "Common", release_year: 2022, price_eur: 0.1 },
  { id: 545, name: "Pikachu", set_name: "SWSH Black Star Promos", card_number: "SWSH234", rarity: "Promo", release_year: 2022, price_eur: 1.13 },
  { id: 434, name: "Pikachu", set_name: "Grand Party", card_number: "", rarity: "", release_year: 2022, price_eur: null },
  { id: 377, name: "Pikachu ex", set_name: "SV-P Promotional", card_number: "001/SV-P", rarity: "ex", release_year: 2023, price_eur: null },
  { id: 427, name: "Pikachu", set_name: "Deck Kit", card_number: "", rarity: "", release_year: 2023, price_eur: null },
  { id: 458, name: "Shibuya\\'s Pikachu", set_name: "Crown Zenith", card_number: "GG30/GG70", rarity: "", release_year: 2023, price_eur: 31.29 },
  { id: 517, name: "Pikachu", set_name: "Indonesia KFC Promo (S-P)", card_number: "016/S-P", rarity: "Promo", release_year: 2023, price_eur: null },
  { id: 518, name: "Pikachu V", set_name: "Indonesia Promo (S-P)", card_number: "377/S-P", rarity: "Promo", release_year: 2023, price_eur: null },
  { id: 259, name: "Pikachu", set_name: "Crown Zenith", card_number: "160/159", rarity: "Secret", release_year: 2023, price_eur: 37.74 },
  { id: 260, name: "Pikachu (Galarian Gallery)", set_name: "Crown Zenith", card_number: "GG30/GG70", rarity: "", release_year: 2023, price_eur: 31.29 },
  { id: 396, name: "Pikachu", set_name: "TCG Live", card_number: "", rarity: "Digital", release_year: 2023, price_eur: null },
  { id: 449, name: "Pikachu", set_name: "Battle Academy", card_number: "", rarity: "", release_year: 2023, price_eur: null },
  { id: 236, name: "Pikachu ex", set_name: "Scarlet & Violet", card_number: "72/198", rarity: "ex", release_year: 2023, price_eur: null },
  { id: 237, name: "Pikachu", set_name: "SV-P Promotional", card_number: "261/SV-P", rarity: "", release_year: 2023, price_eur: null },
  { id: 238, name: "Pikachu", set_name: "SV-P Promotional", card_number: "260/SV-P", rarity: "", release_year: 2023, price_eur: null },
  { id: 378, name: "Pikachu", set_name: "SV-P Promotional", card_number: "050/SV-P", rarity: "", release_year: 2023, price_eur: null },
  { id: 414, name: "Pikachu ex JUMBO", set_name: "SV Jumbo Promo", card_number: "", rarity: "Jumbo", release_year: 2023, price_eur: null },
  { id: 466, name: "Captain Pikachu", set_name: "Gem Pack", card_number: "", rarity: "", release_year: 2023, price_eur: null },
  { id: 379, name: "Pikachu", set_name: "SV-P Promotional", card_number: "075/SV-P", rarity: "", release_year: 2023, price_eur: null },
  { id: 546, name: "Pikachu", set_name: "SWSH Black Star Promos", card_number: "SWSH285", rarity: "Promo", release_year: 2023, price_eur: 1.5 },
  { id: 547, name: "Pikachu", set_name: "SWSH Black Star Promos", card_number: "SWSH286", rarity: "Promo", release_year: 2023, price_eur: 1.24 },
  { id: 239, name: "Pikachu", set_name: "Paldea Evolved", card_number: "62/193", rarity: "Common", release_year: 2023, price_eur: 0.03 },
  { id: 548, name: "Pikachu ex", set_name: "Paldea Evolved", card_number: "63/193", rarity: "Double Rare", release_year: 2023, price_eur: 1.47 },
  { id: 342, name: "Pikachu", set_name: "World Championship 2023", card_number: "", rarity: "Promo", release_year: 2023, price_eur: null },
  { id: 443, name: "Pikachu", set_name: "Pokémon GO Fest", card_number: "", rarity: "Promo", release_year: 2023, price_eur: null },
  { id: 241, name: "Pikachu", set_name: "Obsidian Flames", card_number: "79/197", rarity: "Common", release_year: 2023, price_eur: null },
  { id: 380, name: "Pikachu", set_name: "SV-P Promotional", card_number: "100/SV-P", rarity: "", release_year: 2023, price_eur: null },
  { id: 433, name: "Pikachu with Grey Felt Hat", set_name: "Van Gogh Museum", card_number: "", rarity: "Promo", release_year: 2023, price_eur: null },
  { id: 439, name: "Pikachu", set_name: "McDonald\\'s 2023", card_number: "", rarity: "", release_year: 2023, price_eur: null },
  { id: 440, name: "Pikachu", set_name: "McDonald\\'s 2023", card_number: "", rarity: "", release_year: 2023, price_eur: null },
  { id: 477, name: "Pikachu", set_name: "151", card_number: "25/165", rarity: "Common", release_year: 2023, price_eur: 0.11 },
  { id: 478, name: "Pikachu ex (alt art)", set_name: "151", card_number: "268/165", rarity: "ex", release_year: 2023, price_eur: null },
  { id: 515, name: "Van Gogh Pikachu (Pikachu with Grey Felt Hat)", set_name: "Van Gogh Museum Promo", card_number: "085", rarity: "Promo", release_year: 2023, price_eur: null },
  { id: 240, name: "Pikachu ex (Full Art)", set_name: "151", card_number: "173/165", rarity: "ex", release_year: 2023, price_eur: 44.73 },
  { id: 242, name: "Pikachu", set_name: "Paradox Rift", card_number: "59/182", rarity: "Common", release_year: 2023, price_eur: null },
  { id: 381, name: "Pikachu", set_name: "SV-P Promotional", card_number: "125/SV-P", rarity: "", release_year: 2023, price_eur: null },
  { id: 522, name: "Taipei\\'s Pikachu", set_name: "Taiwan/HK Promo (SV-P)", card_number: "057/SV-P", rarity: "Promo", release_year: 2023, price_eur: null },
  { id: 397, name: "Pikachu ex", set_name: "TCG Live", card_number: "", rarity: "Digital", release_year: 2024, price_eur: null },
  { id: 479, name: "Pikachu (Shiny)", set_name: "Paldean Fates", card_number: "157/091", rarity: "Shiny", release_year: 2024, price_eur: null },
  { id: 243, name: "Pikachu", set_name: "Paldean Fates", card_number: "18/091", rarity: "Common", release_year: 2024, price_eur: 0.06 },
  { id: 444, name: "Pikachu", set_name: "Pokémon GO Tour", card_number: "", rarity: "Promo", release_year: 2024, price_eur: null },
  { id: 519, name: "Pikachu Batik (Staryu Design)", set_name: "Indonesia Journey Promo (SV-P)", card_number: "101/SV-P", rarity: "Promo", release_year: 2024, price_eur: null },
  { id: 523, name: "Lunar New Year Pikachu", set_name: "Taiwan/HK Promo", card_number: "", rarity: "Promo", release_year: 2024, price_eur: null },
  { id: 382, name: "Pikachu", set_name: "SV-P Promotional", card_number: "150/SV-P", rarity: "", release_year: 2024, price_eur: null },
  { id: 441, name: "Pikachu", set_name: "McDonald\\'s 2024", card_number: "", rarity: "", release_year: 2024, price_eur: null },
  { id: 244, name: "Pikachu", set_name: "Temporal Forces", card_number: "51/162", rarity: "Common", release_year: 2024, price_eur: 0.33 },
  { id: 245, name: "Pikachu", set_name: "Twilight Masquerade", card_number: "67/167", rarity: "Common", release_year: 2024, price_eur: null },
  { id: 383, name: "Pikachu ex", set_name: "SV-P Promotional", card_number: "175/SV-P", rarity: "ex", release_year: 2024, price_eur: null },
  { id: 525, name: "Pikachu", set_name: "China Promo (SV-P)", card_number: "001/SV-P", rarity: "Promo", release_year: 2024, price_eur: null },
  { id: 246, name: "Pikachu", set_name: "Shrouded Fable", card_number: "28/064", rarity: "Common", release_year: 2024, price_eur: null },
  { id: 384, name: "Pikachu", set_name: "SV-P Promotional", card_number: "200/SV-P", rarity: "", release_year: 2024, price_eur: null },
  { id: 480, name: "Pikachu", set_name: "Stellar Crown", card_number: "52/142", rarity: "Common", release_year: 2024, price_eur: null },
  { id: 481, name: "Pikachu (Illustration Rare)", set_name: "Stellar Crown", card_number: "231/142", rarity: "IR", release_year: 2024, price_eur: null },
  { id: 520, name: "Pikachu Batik (Xatu Design)", set_name: "Indonesia Journey Promo (SV-P)", card_number: "154/SV-P", rarity: "Promo", release_year: 2024, price_eur: null },
  { id: 521, name: "Pikachu Batik (Flower Design)", set_name: "Indonesia Journey Promo (SV-P)", card_number: "190/SV-P", rarity: "Promo", release_year: 2024, price_eur: null },
  { id: 526, name: "Captain Pikachu (Standard Holo)", set_name: "China Gem Pack Vol. 1", card_number: "CBB1C-0701/09", rarity: "Holo Rare", release_year: 2024, price_eur: null },
  { id: 550, name: "Pikachu (Full Art)", set_name: "China Gem Pack Promo (SV-P)", card_number: "004/SV-P", rarity: "Promo", release_year: 2024, price_eur: null },
  { id: 551, name: "Captain Pikachu (Poké Ball Holo)", set_name: "China Gem Pack Vol. 1", card_number: "CBB1C-0702/09", rarity: "Holo Rare", release_year: 2024, price_eur: null },
  { id: 552, name: "Captain Pikachu (Stars Holo)", set_name: "China Gem Pack Vol. 1", card_number: "CBB1C-0703/09", rarity: "Holo Rare", release_year: 2024, price_eur: null },
  { id: 553, name: "Captain Pikachu (Rotary Holo)", set_name: "China Gem Pack Vol. 1", card_number: "CBB1C-0704/09", rarity: "Holo Rare", release_year: 2024, price_eur: null },
  { id: 554, name: "Captain Pikachu (Master Ball Holo)", set_name: "China Gem Pack Vol. 1", card_number: "CBB1C-0705/09", rarity: "Holo Rare", release_year: 2024, price_eur: null },
  { id: 555, name: "Captain Pikachu (Shiny SSR)", set_name: "China Gem Pack Vol. 1", card_number: "CBB1C-0706/09", rarity: "SSR", release_year: 2024, price_eur: null },
  { id: 556, name: "Captain Pikachu (Stamped Commemorative)", set_name: "China Gem Pack Vol. 1", card_number: "CBB1C-0707/09", rarity: "Promo", release_year: 2024, price_eur: null },
  { id: 557, name: "Captain Pikachu (Full Art SR)", set_name: "China Gem Pack Vol. 1", card_number: "CBB1C-0708/09", rarity: "SR", release_year: 2024, price_eur: null },
  { id: 558, name: "Captain Pikachu & Friede (Secret Rare)", set_name: "China Gem Pack Vol. 1", card_number: "CBB1C-0709/09", rarity: "SR", release_year: 2024, price_eur: null },
  { id: 247, name: "Pikachu ex", set_name: "Stellar Crown", card_number: "93/142", rarity: "ex", release_year: 2024, price_eur: null },
  { id: 524, name: "5th Anniversary Pikachu", set_name: "Taiwan/HK Promo", card_number: "", rarity: "Promo", release_year: 2024, price_eur: null },
  { id: 482, name: "Pikachu", set_name: "Surging Sparks", card_number: "62/191", rarity: "Common", release_year: 2024, price_eur: null },
  { id: 483, name: "Pikachu (Special)", set_name: "Surging Sparks", card_number: "245/191", rarity: "", release_year: 2024, price_eur: null },
  { id: 549, name: "Pikachu ex", set_name: "Surging Sparks", card_number: "57/191", rarity: "Double Rare", release_year: 2024, price_eur: 4.55 },
  { id: 385, name: "Pikachu", set_name: "SV-P Promotional", card_number: "225/SV-P", rarity: "", release_year: 2024, price_eur: null },
  { id: 484, name: "Pikachu ex", set_name: "Prismatic Evolutions", card_number: "28/131", rarity: "Double Rare", release_year: 2025, price_eur: null },
  { id: 485, name: "Pikachu (Full Art)", set_name: "Prismatic Evolutions", card_number: "257/163", rarity: "", release_year: 2025, price_eur: null },
  { id: 486, name: "Pikachu VMAX", set_name: "Prismatic Evolutions", card_number: "258/163", rarity: "VMAX", release_year: 2025, price_eur: null },
  { id: 487, name: "Pikachu (Hyper Rare)", set_name: "Prismatic Evolutions", card_number: "289/163", rarity: "", release_year: 2025, price_eur: null },
  { id: 527, name: "Pikachu AR", set_name: "China Collect 151 Journey", card_number: "170/151", rarity: "AR", release_year: 2025, price_eur: null },
  { id: 528, name: "Pikachu & Psyduck AR", set_name: "China Collect 151 Hope", card_number: "173/151", rarity: "AR", release_year: 2025, price_eur: 44.73 },
  { id: 460, name: "Pikachu", set_name: "Journey Together", card_number: "45/139", rarity: "Common", release_year: 2025, price_eur: null },
  { id: 461, name: "Pikachu ex", set_name: "Destined Rivals", card_number: "78/162", rarity: "ex", release_year: 2025, price_eur: null },
  { id: 529, name: "Pikachu & Gengar AR", set_name: "China Collect 151 Surprise", card_number: "", rarity: "AR", release_year: 2025, price_eur: null },
  { id: 462, name: "Pikachu", set_name: "Mega Evolution", card_number: "52/158", rarity: "Common", release_year: 2025, price_eur: null },
  { id: 559, name: "Pikachu (Standard Holo)", set_name: "China Gem Pack Vol. 4", card_number: "CBB4C-0101/07", rarity: "Holo Rare", release_year: 2025, price_eur: null },
  { id: 560, name: "Pikachu (Poké Ball Holo)", set_name: "China Gem Pack Vol. 4", card_number: "CBB4C-0102/07", rarity: "Holo Rare", release_year: 2025, price_eur: null },
  { id: 561, name: "Pikachu (Stars Holo)", set_name: "China Gem Pack Vol. 4", card_number: "CBB4C-0103/07", rarity: "Holo Rare", release_year: 2025, price_eur: null },
  { id: 562, name: "Pikachu (Rotary Holo)", set_name: "China Gem Pack Vol. 4", card_number: "CBB4C-0104/07", rarity: "Holo Rare", release_year: 2025, price_eur: null },
  { id: 563, name: "Pikachu (Master Ball Holo)", set_name: "China Gem Pack Vol. 4", card_number: "CBB4C-0105/07", rarity: "Holo Rare", release_year: 2025, price_eur: null },
  { id: 564, name: "Pikachu (Shiny)", set_name: "China Gem Pack Vol. 4", card_number: "CBB4C-0106/07", rarity: "SSR", release_year: 2025, price_eur: null },
  { id: 565, name: "Pikachu (Special Full Art)", set_name: "China Gem Pack Vol. 4", card_number: "CBB4C-0107/07", rarity: "SR", release_year: 2025, price_eur: null },
  { id: 463, name: "Pikachu", set_name: "Phantasmal Flames", card_number: "61/174", rarity: "Common", release_year: 2025, price_eur: null },
  { id: 504, name: "Pikachu", set_name: "SV-P Promotional", card_number: "250/SV-P", rarity: "", release_year: 2026, price_eur: null },
  { id: 490, name: "Pikachu", set_name: "Ascended Heroes", card_number: "62/154", rarity: "Common", release_year: 2026, price_eur: null },
  { id: 430, name: "Pikachu", set_name: "30th Anniversary", card_number: "", rarity: "Promo", release_year: 2026, price_eur: null },
  { id: 488, name: "Pikachu (Pokémon Day stamp)", set_name: "Pokémon Day 2026", card_number: "", rarity: "Promo", release_year: 2026, price_eur: null },
  { id: 505, name: "Pikachu", set_name: "SV-P Promotional", card_number: "275/SV-P", rarity: "", release_year: 2026, price_eur: null },
  { id: 489, name: "Pikachu", set_name: "Journey Together", card_number: "45/139", rarity: "Common", release_year: 2026, price_eur: null },
  { id: 491, name: "Pikachu", set_name: "Perfect Order", card_number: "58/142", rarity: "Common", release_year: 2026, price_eur: null },
  { id: 530, name: "Captain Pikachu & Friede (Illustration Rare)", set_name: "China Gem Pack Vol. 5", card_number: "CBB5C-0107/07", rarity: "IR", release_year: 2026, price_eur: null },
  { id: 566, name: "Captain Pikachu (Standard Holo)", set_name: "China Gem Pack Vol. 5", card_number: "CBB5C-0101/07", rarity: "Holo Rare", release_year: 2026, price_eur: null },
  { id: 567, name: "Captain Pikachu (Poké Ball Holo)", set_name: "China Gem Pack Vol. 5", card_number: "CBB5C-0102/07", rarity: "Holo Rare", release_year: 2026, price_eur: null },
  { id: 568, name: "Captain Pikachu (Stars Holo)", set_name: "China Gem Pack Vol. 5", card_number: "CBB5C-0103/07", rarity: "Holo Rare", release_year: 2026, price_eur: null },
  { id: 569, name: "Captain Pikachu (Rotary Holo)", set_name: "China Gem Pack Vol. 5", card_number: "CBB5C-0104/07", rarity: "Holo Rare", release_year: 2026, price_eur: null },
  { id: 570, name: "Captain Pikachu (Master Ball Holo)", set_name: "China Gem Pack Vol. 5", card_number: "CBB5C-0105/07", rarity: "Holo Rare", release_year: 2026, price_eur: null },
  { id: 571, name: "Captain Pikachu (Shiny)", set_name: "China Gem Pack Vol. 5", card_number: "CBB5C-0106/07", rarity: "SSR", release_year: 2026, price_eur: null },
  { id: 492, name: "Pikachu", set_name: "Chaos Rising", card_number: "54/167", rarity: "Common", release_year: 2026, price_eur: null },
  { id: 493, name: "Pikachu (Illustration Rare)", set_name: "Chaos Rising", card_number: "234/167", rarity: "IR", release_year: 2026, price_eur: null },
  { id: 501, name: "Pikachu (Mega Lucario box)", set_name: "Premium Collection", card_number: "", rarity: "Promo", release_year: 2026, price_eur: null },
  { id: 502, name: "Pikachu (Mega Zygarde box)", set_name: "Premium Collection", card_number: "", rarity: "Promo", release_year: 2026, price_eur: null },
  { id: 506, name: "Pikachu", set_name: "Ninja Spinner", card_number: "032/073", rarity: "", release_year: 2026, price_eur: null },
  { id: 507, name: "Pikachu", set_name: "Abyss Eye", card_number: "028/068", rarity: "", release_year: 2026, price_eur: null },
  { id: 511, name: "Pikachu (ETB promo)", set_name: "Chaos Rising ETB", card_number: "", rarity: "Promo", release_year: 2026, price_eur: null },
  { id: 508, name: "Pikachu", set_name: "SV-P Promotional", card_number: "300/SV-P", rarity: "", release_year: 2026, price_eur: null },
  { id: 503, name: "Pikachu", set_name: "First Partner Series 2", card_number: "", rarity: "IR", release_year: 2026, price_eur: null },
  { id: 494, name: "Pikachu", set_name: "Pitch Black", card_number: "48/158", rarity: "Common", release_year: 2026, price_eur: null },
  { id: 495, name: "Pikachu (Full Art)", set_name: "Pitch Black", card_number: "219/158", rarity: "", release_year: 2026, price_eur: null },
  { id: 512, name: "Pikachu (ETB promo)", set_name: "Pitch Black ETB", card_number: "", rarity: "Promo", release_year: 2026, price_eur: null },
  { id: 509, name: "Pikachu", set_name: "SV-P Promotional", card_number: "325/SV-P", rarity: "", release_year: 2026, price_eur: null },
  { id: 510, name: "Pikachu (30th Anniversary)", set_name: "30th Anniversary Collection", card_number: "", rarity: "", release_year: 2026, price_eur: null },
  { id: 496, name: "Pikachu (30th Anniversary)", set_name: "30th Celebration", card_number: "025/200", rarity: "Holo", release_year: 2026, price_eur: null },
  { id: 497, name: "Pikachu & Zekrom-GX (30th stamp)", set_name: "30th Celebration", card_number: "157/200", rarity: "GX", release_year: 2026, price_eur: null },
  { id: 498, name: "Pikachu (Classic Collection)", set_name: "30th Celebration", card_number: "CC-15/CC-30", rarity: "", release_year: 2026, price_eur: null },
  { id: 499, name: "Pikachu (Illustration Rare)", set_name: "30th Celebration", card_number: "268/200", rarity: "IR", release_year: 2026, price_eur: null },
  { id: 500, name: "Pikachu (Hyper Rare)", set_name: "30th Celebration", card_number: "301/200", rarity: "", release_year: 2026, price_eur: null }
]
